GET http://localhost:8080/ HTTP/1.1

###

GET http://localhost:8080/items/1 HTTP/1.1

###

GET http://localhost:8080/items?category=1&brand=1 HTTP/1.1

###

POST http://localhost:8080/account/register HTTP/1.1
content-type: application/json

{
  "username": "matt16",
  "password": "123111",
  "password2": "123111",
  "gender": 1
}

###

POST http://localhost:8080/account/login HTTP/1.1
content-type: application/json

{
  "username": "matt5",
  "password": "123"
}

###

POST http://localhost:8080/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "title": "111",
  "content": "223"
}

###

GET http://localhost:8080/blogs/1 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/blogs/user/1?offset=0 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/blogs/user/1/count HTTP/1.1
content-type: application/json

###

PUT http://localhost:8080/blogs/36 HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "title": "aaa",
  "content": "bbccc"
}

###

DELETE http://localhost:8080/blogs/35 HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c
