GET http://localhost:8080/ HTTP/1.1

### 获取指定商品

GET http://localhost:8080/items/71 HTTP/1.1

### 商品列表（按category/brand过滤）

GET http://localhost:8080/items?category=1&brand=1 HTTP/1.1

### 注册

POST http://localhost:8080/account/register HTTP/1.1
content-type: application/json

{
  "username": "matt16",
  "password": "123111",
  "password2": "123111",
  "gender": 1
}

### 登录

POST http://localhost:8080/account/login HTTP/1.1
content-type: application/json

{
  "username": "matt5",
  "password": "123"
}


### 按位置(offset)列表

GET http://localhost:8080/blogs/?offset=0 HTTP/1.1
content-type: application/json

### 获得blog数量

GET http://localhost:8080/blogs/count HTTP/1.1
content-type: application/json


### 创建blog

POST http://localhost:8080/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "title": "111",
  "content": "223"
}

### 获取指定blog

GET http://localhost:8080/blogs/1 HTTP/1.1
content-type: application/json

###  按位置(offset)获取指定用户blog列表

GET http://localhost:8080/blogs/user/1?offset=0 HTTP/1.1
content-type: application/json

### 获取某用户blog数量

GET http://localhost:8080/blogs/user/1/count HTTP/1.1
content-type: application/json

### 更新blog

PUT http://localhost:8080/blogs/36 HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "title": "aaa",
  "content": "bbccc"
}

### 删除blog

DELETE http://localhost:8080/blogs/35 HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

### 获取所有品牌
GET http://localhost:8080/brands HTTP/1.1
content-type: application/json

### 获取指定品牌
GET http://localhost:8080/brands/1 HTTP/1.1
content-type: application/json

### 获取所有分类
GET http://localhost:8080/categories HTTP/1.1
content-type: application/json

### 获取指定分类
GET http://localhost:8080/categories/1 HTTP/1.1
content-type: application/json

### 获取购物车
GET http://localhost:8080/cart HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

### 添加购物车
POST http://localhost:8080/cart/add HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "itemId":1, "number": 2
}

### 设置购物车
POST http://localhost:8080/cart/set HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c

{
  "itemId":1, "number": 2
}

### 清空购物车
DELETE http://localhost:8080/cart HTTP/1.1
content-type: application/json
Authorization: Bearer 76c62250-8667-11e8-a258-4d497283943c
